# Generated by Django 5.2.13 on 2026-04-14 01:28

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("signup", "Cadastro"),
                            ("phone_verify", "Verificação de telefone"),
                            ("email_verify", "Verificação de email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Código OTP",
                "verbose_name_plural": "Códigos OTP",
                "db_table": "accounts_otp_code",
                "indexes": [
                    models.Index(
                        fields=["identifier", "is_used", "expires_at"],
                        name="accounts_ot_identif_a1cd5a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Cliente"),
                            ("provider", "Prestador"),
                            ("admin", "Administrador"),
                            ("staff", "Colaborador"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("google", "Google"),
                            ("apple", "Apple"),
                            ("whatsapp_otp", "WhatsApp OTP"),
                            ("phone_otp", "SMS OTP"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "accounts_user",
                "indexes": [
                    models.Index(fields=["phone_number"], name="accounts_us_phone_n_613c4a_idx"),
                    models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
                ],
            },
        ),
    ]
