# Generated by Django 5.2.13 on 2026-04-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="buffer_after",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minutos de buffer após o término do serviço (afeta disponibilidade).",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_online",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Se falso, o serviço não aparece para agendamento online público.",
            ),
        ),
    ]
