# Generated by Django 5.2.13 on 2026-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "providers",
            "0007_rename_providers_st_provide_is_active_idx_providers_s_provide_fdfcd3_idx",
        ),
        ("services", "0003_service_new_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="staff_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                through="providers.ServiceStaff",
                to="providers.staff",
            ),
        ),
    ]
