# Generated by Django 5.2.13 on 2026-04-16 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0002_appointment_cancelled_at_appointment_cancelled_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppInboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("wamid", models.CharField(db_index=True, max_length=255, unique=True)),
                ("from_phone", models.CharField(max_length=32)),
                ("body", models.TextField(blank=True)),
                ("message_type", models.CharField(blank=True, max_length=32)),
                ("button_payload", models.CharField(blank=True, max_length=255)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("action_taken", models.CharField(blank=True, max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_whatsapp_messages",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_whatsapp_inbound_message",
                "indexes": [
                    models.Index(
                        fields=["processed", "received_at"], name="webhooks_wh_process_b0f38b_idx"
                    )
                ],
            },
        ),
    ]
