# Generated by Django 5.2.13 on 2026-04-14 22:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoria de Serviço",
                "verbose_name_plural": "Categorias de Serviço",
                "db_table": "providers_service_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
                ("address_street", models.CharField(blank=True, max_length=200)),
                ("address_city", models.CharField(blank=True, max_length=200)),
                ("address_state", models.CharField(blank=True, max_length=200)),
                ("address_zip", models.CharField(blank=True, max_length=10)),
                (
                    "address_lat",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "address_lng",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("timezone", models.CharField(default="America/Sao_Paulo", max_length=50)),
                ("default_appointment_duration", models.PositiveSmallIntegerField(default=60)),
                ("default_buffer_time", models.PositiveSmallIntegerField(default=0)),
                ("max_advance_days", models.PositiveSmallIntegerField(default=60)),
                ("min_notice_hours", models.PositiveSmallIntegerField(default=2)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("instagram_handle", models.CharField(blank=True, max_length=100)),
                ("website_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="providers",
                        to="providers.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Prestador",
                "verbose_name_plural": "Perfis de Prestadores",
                "db_table": "providers_provider_profile",
                "indexes": [
                    models.Index(
                        fields=["is_published", "slug"], name="providers_p_is_publ_1da163_idx"
                    )
                ],
            },
        ),
    ]
