# Generated by Django 5.2.13 on 2026-04-20 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0006_update_staff_fk_working_hours_schedule_block"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="staff",
            new_name="providers_s_provide_fdfcd3_idx",
            old_name="providers_st_provide_is_active_idx",
        ),
    ]
