# Generated by Django 5.2.13 on 2026-04-20 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_rename_providers_st_provide_is_active_idx_providers_s_provide_fdfcd3_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_phone', models.CharField(db_index=True, max_length=32)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_client_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_client_notes', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'providers_client_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'client_phone', '-created_at'], name='providers_c_provide_7fab0e_idx')],
            },
        ),
    ]
