# Generated by Django 5.2.13 on 2026-04-16 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("providers", "0002_add_working_hours_and_schedule_block"),
        ("services", "0002_agendamento_online_cliente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("client_phone", models.CharField(max_length=32)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Pendente confirmação"),
                            ("confirmed", "Confirmado"),
                            ("cancelled", "Cancelado"),
                            ("completed", "Concluído"),
                            ("no_show", "Não compareceu"),
                            ("awaiting_payment", "Aguardando pagamento"),
                        ],
                        db_index=True,
                        default="pending_confirmation",
                        max_length=32,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Telefone"),
                            ("walk_in", "Presencial"),
                            ("imported", "Importado"),
                        ],
                        default="online",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "price_at_booking",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("deposit_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "db_table": "appointments_appointment",
            },
        ),
        migrations.CreateModel(
            name="AppointmentStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32, null=True)),
                ("to_status", models.CharField(max_length=32)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de status",
                "verbose_name_plural": "Históricos de status",
                "db_table": "appointments_appointment_status_history",
                "ordering": ["changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["provider", "start_datetime", "end_datetime"],
                name="appointment_provide_4cbbb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["public_id"], name="appointment_public__0a7dc8_idx"),
        ),
    ]
