# Generated by Django 5.2.13 on 2026-04-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_agendamento_online_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[("client", "Cliente"), ("provider", "Prestador"), ("system", "Sistema")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_1h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
