# Generated by Django 5.2.13 on 2026-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_appointment_cancelled_at_appointment_cancelled_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
