# Generated by Django 5.2.13 on 2026-04-16 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0002_appointment_cancelled_at_appointment_cancelled_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp")], max_length=32)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("confirmation_request", "Confirmacao de agendamento"),
                            ("new_appointment_provider", "Novo agendamento para prestador"),
                            ("confirmed_ack", "Confirmacao recebida"),
                            ("cancelled_provider", "Cancelamento para prestador"),
                            ("reminder_24h", "Lembrete 24h"),
                            ("reminder_1h", "Lembrete 1h"),
                            ("reschedule_link", "Link de reagendamento"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("delivered", "Entregue"),
                            ("read", "Lido"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("template_name", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "indexes": [
                    models.Index(
                        fields=["appointment", "type"], name="notificatio_appoint_2b1cc7_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="notificatio_status_9a4505_idx"
                    ),
                ],
            },
        ),
    ]
